"""add nationality

Revision ID: 710613e8bc89
Revises: 8f3e96347c7b
Create Date: 2024-01-11 10:22:01.019955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '710613e8bc89'
down_revision = '8f3e96347c7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nationality', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_column('nationality')

    # ### end Alembic commands ###
